function [fitresult, gof] = createFitExp(x, y)
%CREATEFIT1(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Sep-2019 11:39:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [0.230488160211558 0.844308792695389 0.194764289567049];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
f = figure(1);
x_fit = 1:0.01:100;
y_fit = fitresult(x_fit);
plot(xData,yData,'b','MarkerSize',7);
hold on;
plot(x_fit,y_fit,'k','LineWidth',1.4);
legend off
% Label axes
xlabel( 'Episode No.', 'Interpreter', 'none' );
ylabel( 'Accumulated reward', 'Interpreter', 'none' );

set(f, 'Position', [100, 100, 500, 250]);  
set(gca,'xtick',20:20:100);
set(gca,'ytick',0.1:0.1:0.5);
set(gcf,'color','w');
axis([0 80 0 0.42]);


