
close all;
clear all
clc;

tempPath = getTempDataPath();
load(strcat(tempPath,'reward_converge\NetMat40.mat'));
num_episodes = 200;
selected_episodes = [2 10 50 200];

epi = 1:size(NetMat,3);
error = zeros(size(epi));

for i = 1:size(NetMat,3)
    error(i) = sum(sum(abs(NetMat(:,:,end) - NetMat(:,:,i))));   
end

% [fitresult, gof] = createFit(epi,error);
% 
% function [fitresult, gof] = createFit(epi,error)
% %CREATEFIT1(EPI,REWARD)
% %  Create a fit.
% %
% %  Data for 'untitled fit 1' fit:
% %      X Input : epi
% %      Y Output: reward
% %  Output:
% %      fitresult : a fit object representing the fit.
% %      gof : structure with goodness-of fit info.
% %
% %  See also FIT, CFIT, SFIT.
% 
% %  Auto-generated by MATLAB on 30-Aug-2019 19:20:28
% 
% 
% %% Fit: 'untitled fit 1'.
% [xData, yData] = prepareCurveData( epi, error );
% 
% % Set up fittype and options.
% ft = fittype( 'power1' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.StartPoint = [2.49913305241924 -0.573283184550156];
% 
% % Fit model to data.
% [fitresult, gof] = fit( xData, yData, ft, opts );
% 
% % Plot fit with data.
% f = figure( 'Name', 'power fit' );
% set(f, 'Position', [100 100 450 300]);
% h = plot( fitresult, xData, yData );
% legend( h, 'Error vs. episode', 'Fitted curve', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'Episode No', 'Interpreter', 'none' );
% ylabel( 'Error', 'Interpreter', 'none' );
% title('Learning curve')
% grid on
% end
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% close all;
% clear all
% clc;
% 
% tempPath = getTempDataPath();
% load(strcat(tempPath,'accumulated_reward_v3.mat'));
% 
% step_best = 60;
% episode_max = 199;
% real_reward = zeros(episode_max,1);
% 
% for i = 1:length(reward_list)
%     normalized_coeff = step_best/step_list(i);
%     real_reward(i) = normalized_coeff * reward_list(i);   
% end
% 
% x = 1:episode_max;
% y = real_reward(1:episode_max);
% 
% [fitresult, gof] = createFitExp(x, y);
% export_fig(strcat(tempPath,'accumulated_reward.pdf'));
% % export_fig(strcat(tempPath,'accumulated_reward.png'),'-r600');